openapi: "3.0.0"
info:
  version: 1.0.0
  title: Google Search
servers:
  - url: http://localhost:8080/api
paths:
  /resources:
    get:
      operationId: search
      tags:
        - search
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An array of resources
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resources"
components:
  schemas:
    Resource:
      type: object
      required:
        - id
        - title
        - link
        - description
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        link:
          type: string
        description:
          type: string
    Resources:
      type: array
      items:
        $ref: "#/components/schemas/Resource"