name: Docker Publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: ./tools/github-action
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_REPO }}
          tag_with_ref: true
          add_git_labels: true
