name: Maven Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      ##################################################################################################################
      # Clone
      ##################################################################################################################
      - name: Clone
        uses: actions/checkout@v2

      ##################################################################################################################
      # Setup
      ##################################################################################################################
      - name: Setup - Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - run: curl -SsL https://downloads.gauge.org/stable | sh -s -- --location-[custom path]
      - run: gauge install java
      - run: gauge install screenshot
      - run: gauge install html-report
      - name: Cache local Maven repository

      ##################################################################################################################
      # Restore Cache
      ##################################################################################################################
      - name: Cache - Maven
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      ##################################################################################################################
      # Maven
      ##################################################################################################################
      - name: Maven - deploy
        run: mvn -B clean deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
